name: Rust release check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update stable && rustup default stable
    - name: Install gdk-3.0
      run: sudo apt install -y libgdk3.0-cil-dev
    - name: Install libsoup2
      run: sudo apt install -y libsoup2.4-dev
    - name: Install libjavascriptcoregtk
      run: sudo apt install -y libjavascriptcoregtk-4.0-dev
    - name: Install libwebkit2gtk
      run: sudo apt install -y libwebkit2gtk-4.0-dev
    - name: Install librsvg2
      run: sudo apt install -y librsvg2-dev
    - name: Install libssl
      run: sudo apt install -y libssl-dev
    - name: Check
      run: cargo check --release --verbose
    - name: Run tests
      run: cargo test --verbose