name: Rust development check

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update stable && rustup default stable
    - name: Install gdk-3.0
      run: sudo apt install -y libgdk3.0-cil-dev
    - name: Install libsoup2
      run: sudo apt install -y libsoup2.4-dev
    - name: Install libjavascriptcoregtk
      run: sudo apt install -y libjavascriptcoregtk-4.0-dev
    - name: Install libwebkit2gtk
      run: sudo apt install -y libwebkit2gtk-4.0-dev
    - name: Install librsvg2
      run: sudo apt install -y librsvg2-dev
    - name: Install libssl
      run: sudo apt install -y libssl-dev
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose
  beta:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update beta && rustup default beta
    - name: Setup formatter
      run: rustup component add rustfmt --toolchain beta
    - name: Install gdk-3.0
      run: sudo apt install -y libgdk3.0-cil-dev
    - name: Install libsoup2
      run: sudo apt install -y libsoup2.4-dev
    - name: Install libjavascriptcoregtk
      run: sudo apt install -y libjavascriptcoregtk-4.0-dev
    - name: Install libwebkit2gtk
      run: sudo apt install -y libwebkit2gtk-4.0-dev
    - name: Install librsvg2
      run: sudo apt install -y librsvg2-dev
    - name: Install libssl
      run: sudo apt install -y libssl-dev
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose
  nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update nightly && rustup default nightly
    - name: Setup formatter
      run: rustup component add rustfmt --toolchain nightly
    - name: Install gdk-3.0
      run: sudo apt install -y libgdk3.0-cil-dev
    - name: Install libsoup2
      run: sudo apt install -y libsoup2.4-dev
    - name: Install libjavascriptcoregtk
      run: sudo apt install -y libjavascriptcoregtk-4.0-dev
    - name: Install libwebkit2gtk
      run: sudo apt install -y libwebkit2gtk-4.0-dev
    - name: Install librsvg2
      run: sudo apt install -y librsvg2-dev
    - name: Install libssl
      run: sudo apt install -y libssl-dev
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose