name: Rust development check

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update stable && rustup default stable
    - name: Install dependencies
      run: sudo apt-get install --no-install-recommends -y libgdk3.0-cil-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose
  beta:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update beta && rustup default beta
    - name: Setup formatter
      run: rustup component add rustfmt --toolchain beta
    - name: Install dependencies
      run: sudo apt-get install --no-install-recommends -y libgdk3.0-cil-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose
  nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update nightly && rustup default nightly
    - name: Setup formatter
      run: rustup component add rustfmt --toolchain nightly
    - name: Install dependencies
      run: sudo apt-get install --no-install-recommends -y libgdk3.0-cil-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose