name: Rust release check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update stable && rustup default stable
    - name: Install dependencies
      run: sudo apt-get install --no-install-recommends -y libgdk3.0-cil-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
    - name: Check
      run: cargo check --release --verbose
    - name: Run tests
      run: cargo test --verbose